### ISSUE TITLE
内网穿透失败

### ISSUE THREAD

**Issue by v7lin** [fatedier/frp#1027]
Issue is only used for submiting bug report and documents typo. If there are same issues or answers can be found in documents, we will close it directly.
(为了节约时间，提高处理问题的效率，不按照格式填写的 issue 将会直接关闭。)

Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST

**What version of frp are you using (./frpc -v or ./frps -v)?**
0.22.0

**What operating system and processor architecture are you using (`go env`)?**

**Configures you used:**
````
  traefik-frpc-http:
    image: v7lin/frpc:0.22.0
    networks:
      - frpc
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
    command:
      - "http"
      - "--proxy_name=traefik-frpc-http"
      - "--local_ip=traefik"
      - "--local_port=80"
      - "--custom_domain=traefik.frpc.${SERVER_DOMAIN:-localhost},portainer.frpc.${SERVER_DOMAIN:-localhost},discuz.${SERVER_DOMAIN:-localhost},demo.${SERVER_DOMAIN:-localhost}"
      - "--server_addr=${FRP_SERVER_DOMAIN:-host.docker.internal}:7000"
      - "--token=${FRP_TOKEN:-xyzfrpsxyz}"
#      - "--log_level=info"
    depends_on:
      - traefik
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=false"

  traefik-frpc-https:
    image: v7lin/frpc:0.22.0
    networks:
      - frpc
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
    command:
      - "https"
      - "--proxy_name=traefik-frpc-https"
      - "--local_ip=traefik"
      - "--local_port=443"
      - "--custom_domain=traefik.frpc.${SERVER_DOMAIN:-localhost},portainer.frpc.${SERVER_DOMAIN:-localhost},discuz.${SERVER_DOMAIN:-localhost},demo.${SERVER_DOMAIN:-localhost}"
      - "--server_addr=${FRP_SERVER_DOMAIN:-host.docker.internal}:7000"
      - "--token=${FRP_TOKEN:-xyzfrpsxyz}"
#      - "--log_level=info"
    depends_on:
      - traefik
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=false"
````

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
traefik-frpc-http 无法向 dashboard 注册
traefik-frpc-https 能向 dashboard 注册

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
````
2018/12/28 20:06:55 [W] [control.go:141] [traefik-frpc-http] start error: router config conflict,
2018/12/28 20:05:16 [W] [control.go:141] [traefik-frpc-http] start error: router config conflict
````

**Can you point out what caused this issue (optional)**
