### ISSUE TITLE
stcp with frpc run by docker fail 容器中运行frpc的stcp功能无法访问

### ISSUE THREAD

**Issue by fanlix** [fatedier/frp#1997]
使用stcp, 在A机透过frps访问B机的端口.
如果A机中的frpc运行在docker中, 则A机**无法访问到B机**

**难道stcp对docker的端口映射有什么特殊要求?**

### 环境:
* frp version:  0.33.0
* os: ubuntu16.04 and centos8
* docker: Docker version 19.03.13, build 4484c46d9d

相同环境下的参考:
* 在OS中直接运行的frpc进行stcp代理, 可正常访问到B机
* docker exec 进入frpc的docker容器内部, 可正常访问到B机
* 使用docker运行的frps正常

### frpc-B.ini
```
[common]
server_addr = xxxx
server_port = 7100
authentication_method = token
token = tttt

[gitea_stcp]
type = stcp
sk = ssss
local_ip = 127.0.0.1
local_port = 30022
```

### frpc-A.ini
```
[common]
server_addr = xxxx
server_port = 7100
authentication_method = token
token = tttt

# access B.30022 by frps
[gitea_stcp_visitor]
type = stcp
role = visitor
server_name = gitea_stcp
sk = sssss
bind_addr = 127.0.0.1
bind_port = 7122
```

### A机的docker-compose.yml
```
version: "3"

services:
  frpc:
    image: "xxxxx/frp"
    container_name: "frpc"
    ports:
      - 127.0.0.1:7122:7122
      - 7123:7122
    volumes:
      - ./cfg:/cfg
    command: ./frpc -c /cfg/frpc.ini
```

### A机docker启动logs
```
frpc    | 2020/09/21 08:18:06 [I] [service.go:282] [b5db0188f06e3227] login to server success, get run id [b5db0188f06e3227], server udp port [0]
frpc    | 2020/09/21 08:18:06 [I] [visitor_manager.go:86] [b5db0188f06e3227] start visitor success
frpc    | 2020/09/21 08:18:06 [I] [visitor_manager.go:130] [b5db0188f06e3227] visitor added: [gitea_stcp_visitor]
```
* ssh connect  fail
```
$ ssh -p 7122 abc@127.0.0.1
kex_exchange_identification: read: Connection reset by peer
$ nc 127.0.0.1  7122
可连接,无返回值
```
