### ISSUE TITLE
Frpc docker image error: unknown command "./frpc" for "frpc"

### ISSUE THREAD

**Issue by fredericmalo** [fatedier/frp#2110]
**[REQUIRED] hat version of frp are you using** 

Version: v0.34.3 (latest)

**[REQUIRED] What operating system and processor architecture are you using**
OS: Official Docker image, on macos Catalino
CPU architecture: 64

**[REQUIRED] description of errors**

Please try this docker-compose.yml: 

```
version: "2"
services:
    frpc:
        image: fatedier/frpc:v0.34.3
        container_name: Frpc
        network_mode: "host"
        volumes:
            - ./cfg:/cfg
        command: ./frpc -c /cfg/frpc.ini
```
I'm getting this error: 

Frpc    | Error: unknown command "./frpc" for "frpc"
Frpc    | Run 'frpc --help' for usage.
Frpc exited with code 1

I don't understand as frps docker image works perfectly and seems built the same way as frpc

**confile**

```
[common]
server_addr = xxx
server_port = 7000
dashboard_port = 7500
# dashboard's username and password are both optional，if not set, default is admin.
dashboard_user = admin
dashboard_pwd = admin

[web]
type = http
local_port = 8080
custom_domains = www.example.com

```

I've tried to run frpc directly on my mac. It works perfectly. 
But frpc container  is not working

Thanks, best !
