### ISSUE TITLE
Allow tcpmux (httpconnect) clients to set local_port

### ISSUE THREAD

**Issue by green-codes** [fatedier/frp#2566]
### Describe the feature request

Is it possible to allow `httpconnect` clients to set different `local_port` than `tcpmux_httpconnect_port`? This will open up frp to a lot more use cases, e.g. proxying port 22 to multiple SSH servers on the client side (each with different subdomains). 

### Describe alternatives you've considered

using static tcp port forwarding for each client-side tcp service, which is cumbersome

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [X] Extensions
- [ ] Others

**Comment by fatedier** [comment]
We plan to support this options but it has low priority.

**Comment by green-codes** [comment]
Thanks for replying! Really hope to see this feature at some point. I manage a number of servers (some at different locations so I can’t just cluster them) behind a single frps proxy, and the port configuration is a mess. Allowing TCP mux with subdomains will be a godsend.

**Comment by MasterKe2003** [comment]
这个现在实现了吗

**Comment by fatedier** [comment]
This use case is already supported: frps exposes a single `tcpmuxHTTPConnectPort`, while each `tcpmux` proxy on frpc can configure its own `localIP` and `localPort`. The HTTP CONNECT hostname is used to select the proxy, and the selected proxy forwards the connection to its configured local backend.

For example, multiple proxies can share one frps TCPMux port while using different domains and local ports:

```toml
[[proxies]]
name = "ssh-a"
type = "tcpmux"
multiplexer = "httpconnect"
customDomains = ["machine-a.example.com"]
localPort = 22

[[proxies]]
name = "ssh-b"
type = "tcpmux"
multiplexer = "httpconnect"
customDomains = ["machine-b.example.com"]
localPort = 2222
```

This behavior is also covered by the TCPMux E2E tests, which route several hostnames through one `tcpmuxHTTPConnectPort` to distinct local backend ports.

To clarify the scope: this does not provide multiple `tcpmuxHTTPConnectPort` listeners on frps or dynamic backend-port selection from the CONNECT target port; `localPort` is configured statically per proxy. Closing this issue because the requested per-proxy local port behavior is available.
