### ISSUE TITLE
write message to control connection error: stream closed

### ISSUE THREAD

**Issue by rucciva** [fatedier/frp#2724]
### Bug Description

frpc on a particular machine keep terminating with `write message to control connection error: stream closed` error. Meanwhile it doesn't happen on frpc on other machine (different network). Could it be related to NAT settings or network security?

### frpc Version

v0.38.0

### frps Version

v0.38.0

### System Architecture

linux/amd64

##### docker-compose.yml

```
version: "3.7"
services:
  frps:
    image: fatedier/frps:v0.38.0
    network_mode: host
    restart: always
    volumes:
      - ./frps.ini:/app/frps.ini
 ```

##### frps.ini

```ini
[common]
log_level = trace

bind_port = 7000
bind_udp_port = 7001
kcp_bind_port = 7000

vhost_http_port=80
vhost_https_port=443
```

##### docker-compose.yml

```
version: "3.7"
services:
  frpc:
    image: fatedier/frpc:v0.38.0
    network_mode: host
    restart: always
    volumes:
      - ./frpc.ini:/app/frpc.ini
```
   
##### frpc.ini

```ini
[common]
server_addr = redacted
server_port = 7000
protocol = tcp
log_level = trace

[caddy-203]
type = tcp
local_port = 443
local_ip = 127.0.0.1
remote_port = 54443
proxy_protocol_version = v2

```

#### frps

```
frps_1  | 2021/12/30 08:23:59 [I] [root.go:202] frps uses command line arguments for config
frps_1  | 2021/12/30 08:23:59 [I] [service.go:192] frps tcp listen on 0.0.0.0:7000
frps_1  | 2021/12/30 08:23:59 [I] [root.go:209] frps started successfully
frps_1  | 2021/12/30 08:24:02 [I] [service.go:447] [eb0da52437ec3964] client login info: ip [redacted:44026] version [0.38.0] hostname [] os [linux] arch [amd64]
frps_1  | 2021/12/30 08:24:32 [I] [control.go:307] [eb0da52437ec3964] control writer is closing
frps_1  | 2021/12/30 08:24:32 [I] [control.go:382] [eb0da52437ec3964] client exit success
frps_1  | 2021/12/30 08:24:32 [I] [service.go:447] [eb0da52437ec3964] client login info: ip [redacted:54273] version [0.38.0] hostname [] os [linux] arch [amd64]
```

#### frpc

```
frpc_1  | 2021/12/30 08:24:32 [I] [service.go:301] [eb0da52437ec3964] login to server success, get run id [eb0da52437ec3964], server udp port [0]
frpc_1  | 2021/12/30 08:24:32 [I] [proxy_manager.go:144] [eb0da52437ec3964] proxy added: [caddy-203]
frpc_1  | 2021/12/30 08:24:32 [T] [proxy_wrapper.go:171] [eb0da52437ec3964] [caddy-203] change status from [new] to [wait start]
frpc_1  | 2021/12/30 08:24:32 [D] [control.go:265] [eb0da52437ec3964] read from control connection EOF
frpc_1  | 2021/12/30 08:24:32 [W] [control.go:294] [eb0da52437ec3964] write message to control connection error: stream closed
frpc_1  | 2021/12/30 08:24:32 [I] [service.go:174] [eb0da52437ec3964] try to reconnect to server...
frpc_1  | 2021/12/30 08:24:32 [I] [visitor_manager.go:60] [eb0da52437ec3964] gracefully shutdown visitor manager
```

### Steps to reproduce

1. start frps
2. start frpc
3. wait for a few minute and connection will be terminated
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others
