### ISSUE TITLE
[Question] How to build and sign for windows

### ISSUE THREAD

**Issue by paivaric** [fatedier/frp#2876]
### Describe the feature request

I'm having trouble with anti-virus and I want to build and sign using my certificate.
How to do it? 

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by BecodReyes** [comment]
Reference workflows file

```
  binary:
    name: Build Golang project
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - run: |
          # https://github.com/actions/setup-go/issues/107
          cp -f `which go` /usr/bin/go
      - run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Archive artifacts for frpc
        uses: actions/upload-artifact@v1
        with:
          name: frpc
          path: bin/frpc

      - name: Archive artifacts for frps
        uses: actions/upload-artifact@v1
        with:
          name: frps
          path: bin/frps
```
