### ISSUE TITLE
文档没有更新支持 yaml和json

### ISSUE THREAD

**Issue by wuai1024** [fatedier/frp#3652]
### Describe the feature request

v0.52.0

我看描述中说到后续会移除 ini 的 支持改为支持 yaml和json，但是文档中好像还没看到类似的配置说明

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by beginor** [comment]
感谢大佬，等 yaml 文档更新再跟进。 toml 不熟悉， 还是 yaml 用着顺手

**Comment by xqzr** [comment]
英文文档已更新支持
另外 几种格式之间可互转

**Comment by wuai1024** [comment]
> 英文文档已更新支持 另外 几种格式之间可互转

toml 没用过，我用的更广泛的 yaml 。

目前我试了下，好像不行，配置如下。

``` yaml
common:
  bind_port: 36000
  tcp_mux: true
```

``` yaml
common:
  bindPort: 36000
  tcpMux: true
```

这2种我都试过了。

``` shell
frps -c frps.yaml
```

结果都不对。

<img width="589" alt="image" src="https://github.com/fatedier/frp/assets/13379708/966a1e9b-e5f3-40f2-8312-413bd270306c">
