### ISSUE TITLE
[Feature Request] 服务端插件 RPC 支持通过 UDS 连接

### ISSUE THREAD

**Issue by xqzr** [fatedier/frp#3673]
### Describe the feature request

通过 unix 域套接字(UNIX-domain socket)连接。形如🔽
```toml
# frps.toml
bindPort = 7000

[[httpPlugins]]
name = "user-manager"
addr = "unix:/dev/shm/frpLG.socket"
path = "/handler"
ops = ["Login"]

[[httpPlugins]]
name = "port-manager"
addr = "https://unix:/dev/shm/frpNP.socket"
path = "/handler"
ops = ["NewProxy"]
```
UDS 相比 TCP 它没有 IP(IPv4)、TCP 层校验 、0-RTT。

参考：
https://github.com/fatedier/frp/blob/dev/doc/server_plugin.md#server-plugin-configuration
https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass

### Describe alternatives you've considered

通过 IPv6 连接。形如🔽
```toml
[[httpPlugins]]
name = "user-manager"
addr = "[::1]:9000"
path = "/handler"
ops = ["Login"]
```

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others
