### ISSUE TITLE
[Feature Request] 能否配置连续多端口？

### ISSUE THREAD

**Issue by winterant** [fatedier/frp#3800]
### Describe the feature request

能否为配置一个连续的端口区间？或者端口序列？例如：
```
serverAddr = "*************"
serverPort = 8000

[[proxies]]
name = "my-project"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8001-9000
remotePort = 8001-9000
```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
0.52.0 及以上 **不支持**

**Comment by firemakergk** [comment]
在此请求在新版本配置文件中支持对range的支持，这对于webrtc这类流服务的代理至关重要，它的协商接口不确定且是一个范围。

**Comment by scientificworld** [comment]
同上。可否做成类似于这样的配置？不知道 TOML 有没有单独的 range type 之类的东西。

```toml
[[proxies]]
name = "tcp_port"
type = "tcp"
localIP = "127.0.0.1"
localPortRange = "6010-6020,6022,6024-6028"
remotePortRange = "6010-6020,6022,6024-6028"
```
