### ISSUE TITLE
如何设置日志保存到文件，并同时打印到标准输出

### ISSUE THREAD

**Issue by mapxn** [fatedier/frp#3906]
### Describe the feature request

如何保存日志到文件，并同时打印到标准输出
使用0.53.2版本，frps使用如下yml配置，发现只能保存到文件里，标准输出为空
```yml
bindAddr: 0.0.0.0
bindPort: 7000

vhostHTTPPort: 30080
vhostHTTPSPort: 30443

log:
  to: /var/log/frp/frps.log
  level: info
  maxDays: 7
  disablePrintColor: false

```

印象在旧版本中是可以的，是新版本我不会用吗？

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others
