### ISSUE TITLE
使用NPM+FRP，公网ip可以成功，localhost失败？

### ISSUE THREAD

**Issue by A-sunny-boy** [fatedier/frp#3944]
### Bug Description

阿里云作为公网服务器，使用frp对内网的http服务进行代理，然后在阿里服务器上使用NPM根据域名进行流量转发。
阿里云frps配置
```toml
......
vhostHttpPort = 1111
......                        
```
内网frpc配置
```toml
[[proxies]]
name = "gettint-start"
type = "http"
localPort = 3000
customDomains = ["my.domain.xyz"]
```
使用NPM将流量转发到阿里云服务器的公网ip时，可以使用在公网使用`my.domain.xyz`访问到内网服务，NPM配置如下：
![image](https://github.com/fatedier/frp/assets/12973547/f8ab0701-c565-48fc-97ac-7c0bbbccd9a3)

使用NPM将流量转发到localhost或127.0.0.1时，出现502。
![image](https://github.com/fatedier/frp/assets/12973547/a00f4e8f-93a6-4f32-a7e9-3d7614ce7b78)
![image](https://github.com/fatedier/frp/assets/12973547/cee8181c-e48f-4a2c-aa59-7b53dad3c3a4)

请问如何内内网ip访问呢？

### frpc Version

0.53.2

### frps Version

0.53.2

### System Architecture

linux/amd64

### Configurations

frps
......
vhostHttpPort = 1111
......        

frpc
```toml
[[proxies]]
name = "gettint-start"
type = "http"
localPort = 3000
customDomains = ["my.domain.xyz"]
```

### Logs

No log

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [X] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others
