### ISSUE TITLE
udp代理错误

### ISSUE THREAD

**Issue by jinghuashang** [fatedier/frp#3997]
### Bug Description

使用udp端口代理时不生效，但tcp端口协议正常
![](https://imgbed.jinghuashang.cn/file/94ec5921cbc74328cb7bb.png)

### frpc Version

0.54

### frps Version

0.54

### System Architecture

linux/amd64windows/amd64

### Configurations

【frps】
bindPort = 7000

webServer.addr = "0.0.0.0"
webServer.port = 7500
【frpc】
serverAddr = ""
serverPort = 7000

[[proxies]]
privilege_token = true 
name = "L4D2节点0"
type = "udp"
local_ip = "192.168.31.13"
local_port = 27015
remotePort = 27015

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by xqzr** [comment]
https://github.com/fatedier/frp/blob/cf025d63207b4a2872ba946dc32ab56b3f98053a/conf/frpc_full_example.toml#L184-L185

**Comment by jinghuashang** [comment]
> https://github.com/fatedier/frp/blob/cf025d63207b4a2872ba946dc32ab56b3f98053a/conf/frpc_full_example.toml#L184-L185

同上修改并没有用

**Comment by xqzr** [comment]
frps 所在网络 开放 UDP 27015

**Comment by jinghuashang** [comment]
> frps 所在网络 开放 UDP 27015

端口开放了也无效
![](https://imgbed.jinghuashang.cn/file/c8f9b4e0afc4bae7c3d4a.png)

**Comment by WuMe-sicx** [comment]
你解决了吗？

**Comment by freeze-dolphin** [comment]
![image](https://github.com/fatedier/frp/assets/40729044/042ff81c-66dd-4927-a187-43de1ba37128)

UDP 27015端口，看来你也是转发cs2的（

遇到了同样的问题

`frps.toml`:
```toml
bindPort = 7000

webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "alppp"

```

`frpc.toml`:
```toml
serverAddr = "129.211.211.70"
serverPort = 7000

webServer.addr = "127.0.0.1"
webServer.port = 7400
webServer.user = "admin"
webServer.password = ""

[[proxies]]
name = "cs2"
type = "udp"
localIP = "127.0.0.1"
localPort = 27015
remotePort = 6000

```

客户端和服务端都没有任何报错，却没有流量被转发
