### ISSUE TITLE
配置文件修改为 toml 格式后无法通过 ssh 访问 gitlab

### ISSUE THREAD

**Issue by WindSpiritSR** [fatedier/frp#4064]
### Bug Description

1. 三个端都使用 TOML 配置时，无法使用 ssh 访问 gitlab 仓库
2. 保持 1 中配置，将 frpc proxies 绑定的业务切换为普通 ssh server 时可以正常访问
3. 保持 1 中配置，将 frpc visitors 端配置格式切换为 Ini，可以正常通过 gitlab ssh 访问仓库
4. frps 及 frpc proxies 使用 TOML 或 Ini 对测试结果没有影响

### frpc Version

0.55.1

### frps Version

0.55.1

### System Architecture

linux/amd64

## frps

<table>
<tr><th>Ini</th><th>TOML</th></tr>
<tr>
<td>

```ini
[common]
bind_port = 11234
token = token
tls_only = false
```

</td>
<td>

```toml
bindPort = 11234
auth.token = "token"
transport.tls.force = false
```

</td>
</tr>
</table>

## frpc proxies

<table>
<tr><th>Ini</th><th>TOML</th></tr>
<tr>
<td>

```ini
[common]
server_addr = example.com
server_port = 11234
token = token
login_fail_exit = false
tls_enable = true

[gitlab]
type = stcp
local_ip = 10.0.0.1
local_port = 12322
sk = secretkey
```

</td>
<td>

```toml
serverAddr = "example.com"
serverPort = 11234
auth.token = "token"
loginFailExit = false
transport.tls.enable = true

[[proxies]]
name = "gitlab"
type = "stcp"
localIP = "10.0.0.1"
localPort = 12322
secretKey = "secretkey"
```

</td>
</tr>
</table>

## frpc visitors

<table>
<tr><th>Ini</th><th>TOML</th></tr>
<tr>
<td>

```ini
[common]
server_addr = frps_container_name
server_port = 11234
token = token
login_fail_exit = false
tls_enable = true

[gitlab_visitor]
role = visitor
server_name = gitlab
type = stcp
bind_addr = frpc_container_name
bind_port = 11122
sk = secretkey
```

</td>
<td>

```toml
serverAddr = "frps_container_name"
serverPort = 11234
auth.token = "token"
loginFailExit = false
transport.tls.enable = true

[[visitors]]
name = "gitlab_visitor"
serverName = "gitlab"
type = "stcp"
bindAddr = "frpc_container_name"
bindPort = 11122
secretKey = "secretkey"
```

</td>
</tr>
</table>

### Steps to reproduce

`git clone` 返回如下

```
Cloning into 'repo_name'...
ssh: connect to host git.example.com port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

`ssh -vvv -T` 返回如下

```
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
debug1: Reading configuration data C:\\Users\\user/.ssh/config
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug2: resolving "git.example.com" port 22
debug2: ssh_connect_direct
debug1: Connecting to git.example.com [93.184.216.34] port 22.
debug3: finish_connect - ERROR: async io completed with error: 10061, io:0000019AEE04E440
debug1: connect to address 93.184.216.34 port 22: Connection refused
ssh: connect to host git.example.com port 22: Connection refused
```

三个 frp 端均使用 docker 部署，dockerfile 如下

```dockerfile
FROM alpine:3.19.0

ENV TZ=Asia/Shanghai

COPY ./frp_*_linux_amd64.tar.gz /tmp/frp_linux_amd64.tar.gz

WORKDIR /app

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories \
    && apk update \
    && apk upgrade \
    && apk add --no-cache tzdata \
    && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone \
    && tar zxvf /tmp/frp_linux_amd64.tar.gz -C /tmp --strip-components 1 \
    && mv /tmp/frpc /app/frpc \
    && rm -rf /tmp/*

ENTRYPOINT ["./frpc"]

CMD ["-c", "./frpc.toml"]
```

服务器端 frps 及 frpc visitors `docker-compose.yml` 如下

```yml
version: '3'

services:
  frps:
    build:
      context: ./frp/dockerfiles
      dockerfile: frps.Dockerfile
    container_name: frps
    hostname: frps
    volumes:
      - ./frp/config/frps.toml:/app/frps.toml:ro
    ports:
      - '11234:11234'
    networks:
      net:
        priority: 10
        ipv4_address: 172.20.0.1
    restart: unless-stopped
    tty: true

  frpc:
    build:
      context: ./frp/dockerfiles
      dockerfile: frpc.Dockerfile
    container_name: frpc
    hostname: frpc
    volumes:
      - ./frp/config/frpc.toml:/app/frpc.toml:ro
    ports:
      - '22:11122'
    networks:
      net:
        priority: 10
        ipv4_address: 172.20.0.2
    restart: unless-stopped
    tty: true

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
```

局域网 frpc proxies `docker-compose.yml` 如下

```yml
version: '3'

services:
  frpc:
    build:
      context: ./frp/dockerfiles
      dockerfile: frpc.Dockerfile
    container_name: frpc
    hostname: frpc
    volumes:
      - ./frp/config/frpc.toml:/app/frpc.toml:ro
    networks:
      net:
        priority: 10
        ipv4_address: 172.20.0.1
    restart: unless-stopped
    tty: true

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others
