### ISSUE TITLE
remotePort，一直报错

### ISSUE THREAD

**Issue by FanyuanCode** [fatedier/frp#4088]
### Bug Description

一直不识别这个字段配置，为什么呢？

### frpc Version

v0.55.1

### frps Version

latest

### System Architecture

windows/amd64

### Configurations

serverAddr = "###"
serverPort = 9004
auth.token = "###"

[[proxies]]
name = "rdp-fanyuan"
type = "sudp"
localIP = "127.0.0.1"
localPort = 3389
secretKey= "###"
remotePort = 6000

### Logs

日志：
unmarshal ProxyConfig error: json: unknown field "remotePort"
2024/03/20 周三 17:17:21.79: Script executed 

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [X] Others

**Comment by jikunchong** [comment]
type = "sudp" 带 secretKey，没有这个类型吧？
要配置 RDP 穿透，改为 TCP 试试：
```toml
[[proxies]]
name = "rdp-fanyuan"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3389
remotePort = 6000
```
