### ISSUE TITLE
frpc - unmarshal ProxyConfig error: json: unknown field "locations"

### ISSUE THREAD

**Issue by jikunchong** [fatedier/frp#4096]
### Bug Description

I expect to use https://mydomain.com/joplin to access the application.
ref docs: 
- https://github.com/fatedier/frp?tab=readme-ov-file#enable-https-for-a-local-https-service
- https://github.com/fatedier/frp?tab=readme-ov-file#url-routing

but,
```shell
sudo docker logs frpc-mydomain

unmarshal ProxyConfig error: json: unknown field "locations"
```

### frpc Version

docker: fatedier/frpc:v0.56.0

### frps Version

docker: fatedier/frps:v0.56.0

### System Architecture

linux/arm64

### Configurations

```toml
# frpc.toml
[[proxies]]
name = "my-joplin"
type = "https"
#subdomain = "joplin"
customDomains = ["mydomain.com"]
locations = ["/joplin"]
[proxies.plugin]
type = "https2http"
localAddr = "127.0.0.1:8223"
crtPath = "/data/cert/mydomain.com/server.crt"
keyPath = "/data/cert/mydomain.com/server.key"
hostHeaderRewrite = "127.0.0.1"
requestHeaders.set.x-from-where = "frp"
```

### Logs

unmarshal ProxyConfig error: json: unknown field "locations"

### Steps to reproduce

1. nano frpc.toml
2. sudo docker run -d --name frpc-mydomain ...
3. sudo docker logs frpc-mydomain

### Affected area

- [X] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others
