### ISSUE TITLE
unmarshal ProxyConfig error: json: unknown field "customDomains"

### ISSUE THREAD

**Issue by Monkey-xu** [fatedier/frp#4106]
### Bug Description
我更新版本之后，配置没变，就起不来了。

frpc.toml
[[proxies]]
name = "XXXX"
type = "http"
localIp = "192.168.2.101"
subdomain = "x"
customDomains = ["x.xxx.com.cn"]

### frpc Version

0.56.0

### frps Version

0.56.0

### System Architecture

 linux/amd64

### Configurations

frpc.toml
[[proxies]]
name = "XXXX"
type = "http"
localIp = "192.168.2.101"
subdomain = "x"
customDomains = ["x.xxx.com.cn"]

### Logs

frpc  | unmarshal ProxyConfig error: json: unknown field "customDomains"

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [x] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by Geolem** [comment]
我的也是：unmarshal ProxyConfig error: json: unknown field "remotePort"

**Comment by rockiecxh** [comment]
same issue here.

```toml
# frpc configuration

user = "xxx"

serverAddr = "0.0.0.0"
serverPort = 1111

[[proxies]]
name = "x"
type = "http"
localIP = "192.168.1.1"
localPort = 100
customDomains = ["x.com"]
remotePort = 80
transport.useEncryption = true
transport.useCompression = true

```

frpc verify -c ./f.toml
unmarshal ProxyConfig error: json: unknown field "remotePort"
