### ISSUE TITLE
:bug: frp 0.57.0 代理 Jenkins 2.453 时，/blue/rest/search 接口错误

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [fatedier/frp#4163]
### Bug Description

1. 我在使用 frp 0.57.0 代理 Jenkins 2.453 时，发现 /blue/rest/search 接口错误，http、https 都是异常
2. Jenkins 其他功能正常，
3. 直接访问 Jenkins 也正常
4. 访问 http://地址:端口/blue/pipelines/ 即可触发 /blue/rest/search 接口

![20240417-09-45-12-DESKTOP-8E6LUNV-5026-chrome-DiRgOY6WGW](https://github.com/fatedier/frp/assets/46893436/71373da9-8bc1-45df-b557-0ef75130527f)

### frpc Version

0.57.0

### frps Version

0.57.0

### System Architecture

linux/amd64

### Configurations

- frps.toml
```toml
bindPort = xxx
vhostHTTPPort = 80
vhostHTTPSPort = 443
log.to = "/software/logs/frps.log"
auth.method = "token"
auth.token = "xxx"
```

- frpc.toml
```toml
serverAddr = "x.x.x.x"
serverPort = xxx

auth.method = "token"
auth.token = "xxx"

log.to = "/root/frp_0.57.0_linux_amd64/frpc.log"

[[proxies]]
name = "jenkins-http"
type = "http"
localPort = 8080
customDomains = ["xxx"]


[[proxies]]
name = "jenkins-https"
type = "https"
customDomains = ["xxx"]

[proxies.plugin]
type = "https2http"
localAddr = "127.0.0.1:8080"

crtPath = "/root/frp_0.57.0_linux_amd64/jenkins/xxx.crt"
keyPath = "/root/frp_0.57.0_linux_amd64/jenkins/xxx.key"
hostHeaderRewrite = "127.0.0.1"
requestHeaders.set.x-from-where = "frp"
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others
