### ISSUE TITLE
frpc    transport: protocol: kcp 似乎无法在非root权限下运行

### ISSUE THREAD

**Issue by bonjour-py** [fatedier/frp#4179]
### Bug Description

frpc    transport: protocol: kcp 似乎无法在非root权限下运行
os ubuntu desktop 23.10  表现为无法响应

使用sudo 运行正常 

奇怪的是 在 no-root-user on kalilinux in lxd on this ubuntu 运行正常

### frpc Version

0.57.0

### frps Version

ghcr.io/fatedier/frps:v0.56.0

### System Architecture

linux/amd64

### Configurations

```
webServer:
  port: 7000
serverAddr: -----------------------
serverPort: 30200
transport:
  protocol: kcp
auth:
  token: ----------------------
user: ------------
proxies:
  - name: -------------
    type: tcp
    localPort: ------------
    remotePort: 7018
  - name: -------------
    type: udp
    localPort: ----------
    remotePort: 7018
```

### Logs

```
bonjour@work:~/文档/frp$ ./frpc -c config.yaml 
2024-04-24 15:48:41.743 [I] [sub/root.go:142] start frpc service for config file [config.yaml]
2024-04-24 15:48:41.743 [I] [client/service.go:294] try to connect to server...
^C^C^C^C^C^C^Z
[1]+  已停止               ./frpc -c config.yaml
bonjour@work:~/文档/frp$ kill -9 %1

[1]+  已停止               ./frpc -c config.yaml
bonjour@work:~/文档/frp$ 
[1]+  已杀死               ./frpc -c config.yaml
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others
