### ISSUE TITLE
Variable substitution for TOML config in Docker Compose - how to make it happen?

### ISSUE THREAD

**Issue by Kenya-West** [fatedier/frp#4212]
### Bug Description

I try to substitute variables set in `frps.toml.template` file for dockerized frps instance and make Docker to produce `frps.toml` file in mounted dir:

**docker-compose.yml**:
```yaml
version: '3.8'
services:
  frps:
    image: snowdreamtech/frps
    container_name: frps
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config-frps:/etc/frp # there lies frps.toml.template and should have been frps.toml
    network_mode: host

volumes:
  certs:
    external: true
    name: caddy_caddy-certs
```

**.env**:
```dotenv
DOMAIN=example.com      # your domain
FRP_CADDY_PATH=frp                      # must be present, or it produces bugs. Example value: `frps`
FRPS_SERVER_PORT=7000                   # port of the server
FRPS_AUTH_METHOD=token                  # authentication method
FRPS_AUTH_TOKEN=token                      # authentication token
FRPS_DASHBOARD_PORT=7500                # port of the dashboard (server)
FRPS_DASHBOARD_USER=admin           # frps dashboard username
FRPS_DASHBOARD_PASSWORD=admin          # frps dashboard password
FRPC_DASHBOARD_PORT=7400                # port of the dashboard (client)
FRPC_DASHBOARD_USER=admin           # frpc dashboard username
FRPC_DASHBOARD_PASSWORD=admin          # frpc dashboard password
```

config-frps/**frps.toml.template**
```toml
bindPort = ${FRPS_SERVER_PORT}
allowPorts = [
  { start = 22001, end = 22089 }
]
webServer.addr = "0.0.0.0"
webServer.port = ${FRPS_DASHBOARD_PORT}
webServer.user = "${FRPS_DASHBOARD_USER}"
webServer.password = "${FRPS_DASHBOARD_PASSWORD}"
auth.method = "${FRPS_AUTH_METHOD}"
auth.token = "${FRPS_AUTH_TOKEN}"
```

`frps` (or Docker itself) does not substitute variables and does not produce `frps.toml` file inside the container:

```log
frps  | 2024-05-12T10:32:51.902635600Z open /etc/frp/frps.toml: no such file or directory
```

How to force Docker to create `frps.toml` file?

### frpc Version

0.56.1

### frps Version

0.56.1

### System Architecture

linux/amd64

### Configurations

-

### Logs

-

### Steps to reproduce

1. Dockerize `frps`;
2. Define variable in `.env` file;
3. Set the variable as a value in `frps.toml`;
4. `docker compose up -d frps` the instance;
5. See that variable is not substituted.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [X] Server Plugin
- [ ] Extensions
- [ ] Others
