### ISSUE TITLE
nginx 转发请求到 frps 的 HTTPS 时报错 502

### ISSUE THREAD

**Issue by ks4na** [fatedier/frp#4239]
### Bug Description

由于 frp 内网穿透的 HTTPS 服务，需要携带 `vhostHTTPSPort` 指定的端口号（例如：`20443`），所以想要在 frps 所在的机器上通过 nginx 反向代理来隐藏端口号。

所以就有了如下的 `nginx` 请求转发配置（`*.frps.example.com` 已经配置了解析到当前服务器）：

```conf
server {
    listen       80;
    listen  [::]:80;
    server_name *.frps.example.com;

    return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name *.frps.example.com;

  ssl_certificate certs/self_signed/server.crt;
  ssl_certificate_key certs/self_signed/server.key;

  include ssl/ssl_options.conf;

  location / {
    proxy_pass https://127.0.0.1:20443; # 转发到本机的 frps 监听 HTTPS 服务的地址

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
```

想要实现当访问 `https://web-https.frps.example.com` 时，转发请求到 frps 监听 HTTPS 服务的地址 `https://127.0.0.1:20443`，然后根据 `frpc.toml` 中的配置：

```toml
user = "some_user"

serverAddr = "frps.example.com"
serverPort  = 20000

# 内网 HTTPS 服务
[[proxies]]
name = "web-https"
type = "https"
localPort = 443
customDomains = ["web-https.frps.example.com"]
```

将请求转发到内网服务器。

但是这样做会报错 `502`， nginx 反向代理的日志输出如下：

```sh
192.168.1.10 - - [23/May/2024:15:23:01 +0000] "GET /favicon.ico HTTP/2.0" 502 559 "https://web-https.frps.example.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" "-"
2024/05/23 15:23:13 [crit] 49#49: *29 SSL_do_handshake() failed (SSL: error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name:SSL alert number 112) while SSL handshaking to upstream, client: 192.168.1.10, server: web-https.frps.example.com, request: "GET / HTTP/2.0", upstream: "https://127.0.0.1:20443/", host: "web-https.frps.example.com"
```

报错的原因是 `unrecognized name`。

`frps` 的日志输出如下（调整日志等级 `log.level = debug`）：

```sh
2024/05/23 15:23:01 [D] [vhost.go:216] http request for host [] path [] httpUser [] not found
```

对比携带 `20443` 端口的请求时的日志输出:

```sh
2024/05/23 15:28:34 [D] [vhost.go:247] [868cad529d201650] [some_user.web-https] new request host [web-https.frps.example.com] path [] httpUser []
```

发现少了 `host` 的值。

### frpc Version

0.52.3

### frps Version

0.52.3

### System Architecture

linux/amd64

### Configurations

`frps.toml`:

```toml
bindPort = 20000

vhostHTTPPort = 20080
vhostHTTPSPort = 20443
```

`frpc.toml`:
```toml
user = "some_user"

serverAddr = "frps.example.com"
serverPort  = 20000

# 内网 HTTPS 服务
[[proxies]]
name = "web-https"
type = "https"
localPort = 443
customDomains = ["web-https.frps.example.com"]
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others
