### ISSUE TITLE
[Question] Can I use frp to relay all the traffic to a local traefik instance?

### ISSUE THREAD

**Issue by TheZoker** [fatedier/frp#4255]
### Describe the feature request

Hi there,

It's more a questions and less a feature request. I have a local traefik instance, which handles all the SSL and reverse proxy stuff of my subdomains to local hosted applications. 

I would use frp to tunnel all the requests (no matter the domain) from my VPS to my local frp client, which then sends all the requests to traefik. The SSL should be terminated on traefik and not earlier by frp. Is that already possible? 

Config could look like this:
```toml
# frpc.toml
serverAddr = "x.x.x.x"
serverPort = 7000

[[proxies]]
name = "web"
type = "https"
localIP = "<ip-of-traefik>"
localPort = 443
customDomains = ["*"]
```

Thanks in advance!

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others
