### ISSUE TITLE
[Feature Request] Mac 客户端安装包开启frpc和使用docker开启 注意事项

### ISSUE THREAD

**Issue by gexin1** [fatedier/frp#4376]
### Mac 客户端开启frpc注意事项
1. 首先要开启ssh登录
![截屏2024-08-11 01 11 01](https://github.com/user-attachments/assets/95488166-db1f-4980-bb59-8e2f09503719)
2. 然后按照官网配置就可以了
[https://gofrp.org/zh-cn/docs/examples/ssh](https://gofrp.org/zh-cn/docs/examples/ssh/)
### Mac使用docker安装客户端注意
1. 个人使用的是snowdreamtech/frps 由于Mac 不支持
```shell
 --network host
```
所以我们无法在和宿主机器网络互通 
要手动打开端口
```yml
services:
  frpc:
    image: snowdreamtech/frpc:0.59
    container_name: frpc
    restart: always
    # network_mode: host #不支持
    ports:
      - "8080: 8080"
    volumes:
      - /path/to/frpc.toml:/etc/frp/frpc.toml
``` 
2.ssh服务22端口被占用 我们使用**host.docker.internal**来访问宿主机器
注意web地址服务要设置为**0.0.0.0**来接受所有地址的请求
```toml
webServer.addr = "0.0.0.0"
webServer.port = 8080
webServer.user = ""
webServer.password = ""

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "host.docker.internal"
localPort = 22
remotePort = 7000
```

### Affected area

- [X] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others
