### ISSUE TITLE
error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type v1.ClientConfig

### ISSUE THREAD

**Issue by RickoNoNo3** [fatedier/frp#4381]
### Bug Description

Windows，使用toml配置时报错：error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type v1.ClientConfig

根据<https://github.com/fatedier/frp/issues/3859>的方法，检查配置文件格式未发现问题，检查行尾LF或CRLF都无果。

### frpc Version

0.59.0

### frps Version

0.59.0

### System Architecture

windows/adm64

### Configurations

`frpc.toml`:

```toml
serverAddr = "x.x.x.x"
serverPort = 8000
transport.protocol = "websocket"
auth.method = “token"
auth.token = "******"

[[proxies]]
name = "{{.Envs.FRPC_NAME}}"
type = "{{.Envs.FRPC_TYPE}}"
localIP = "127.0.0.1"
localPort = {{.Envs.FRPC_LOCAL_PORT}}
remotePort = {{.Envs.FRPC_REMOTE_PORT}}

transport.useEncryption = true
transport.useCompression = true

```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others
