### ISSUE TITLE
[Feature Request] Support for URI Stripping in HTTP Proxies

### ISSUE THREAD

**Issue by xJetRy** [fatedier/frp#4404]
### Describe the feature request

I am currently using Nginx to forward traffic from ports 80 and 443 to port 8000 and have configured vhostHTTPPort=8000. My client configuration is as follows:
```toml
[[proxies]]
name = "service-1"
type = "http"
localPort = 8081
customDomains = ["www.example.com"]
locations = ["/service-1"]
```
When I make a request to www.example.com/service-1/foo, the service on port 8081 receives the request URI as /service-1/foo instead of the expected /foo. I have reviewed the documentation but have not found a way to configure this behavior.

Is there an existing feature that supports stripping the location prefix from the URI before forwarding the request to the local service? If not, could this feature be considered for future development?

Thank you for your attention to this request.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [X] Developer Infrastructure
- [X] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others
