### ISSUE TITLE
[Feature Request] 如何设置frp让他能够代理在一台内网电脑中的多个http服务

### ISSUE THREAD

**Issue by ddyykk** [fatedier/frp#4469]
### Describe the feature request

我知道可以用子域名的方式来解决, 但这样稍微有些麻烦, 如果能用IP地址就可以少一笔域名的费用了.

我看以前 ini 配置文件时, http代理可以设置多个, 每个使用不同的localPort和remotePort, 现在似乎不能这样做了, 在http代理中设置remotePort参数程序就会报错无法启动.
 以下是我的代码实例:
frps.toml:
```bash
bindPort = 7000
vhostHTTPPort = 8080
# This is the port to use when client try to access the service


auth.method = "token"
auth.token = "xxxxxxx"
```

frpc.toml:
```bash
serverAddr = "x.x.x.x"
serverPort = 7000
auth.method = "token"
auth.token = "xxxxxxx"

[[proxies]]
name = "web1"
type = "http"
localIP = "192.168.3.131"
localPort = 8081
customDomains = ["serverAddr"]

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "192.168.3.131"
localPort = 22
remotePort = 6002
```
如何能增加多个http proxy
```bash
[[proxies]]
name = "web2"
type = "http"
localIP = "192.168.3.131"
localPort = 8082
customDomains = ["serverAddr"]
```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by superzjg** [comment]
试试 `type = "tcp"`

**Comment by ddyykk** [comment]
在frpc.toml加入这一段:
```bash
#[[proxies]]
#name = "service2"
#type = "tcp"
#localIP = "192.168.3.131"
#localPort = 8897
#remotePort = 8897
#customDomains = ["193.x.xx.x"]
```
然后还是启动不成功, 日志中的错误是:
` frpc[27243]: unmarshal ProxyConfig error: json: unknown field "remotePort"`

**Comment by superzjg** [comment]
> 在frpc.toml加入这一段:
> 
> ```shell
> [[proxies]]
> name = "service2"
> type = "tcp"
> localIP = "192.168.3.131"
> localPort = 8897
> remotePort = 8897
> customDomains = ["193.x.xx.x"]
> ```
> 
> 然后还是启动不成功, 日志中的错误是: ` frpc[27243]: unmarshal ProxyConfig error: json: unknown field "remotePort"`
> 
> 似乎remotePort参数只能有一个, 或者tcp proxy只能有一个, ssh 有了就不能再有.

tcp 与 remotePort 相配，与  customDomains 不相容。直接使用 frps 所在服务器的其中一个域名即可，配上端口号使用。

**Comment by ddyykk** [comment]
可以了, 多谢

**Comment by liu1015** [comment]
> 可以了, 多谢

您好，可以看看你的配置吗？我也是没办法实现多个http配置

**Comment by ddyykk** [comment]
```toml
serverAddr = "x.x.x.x"
serverPort = 7000
auth.method = "token"
auth.token = "xxxxxxx"

[[proxies]]
name = "web1"
type = "http"
localIP = "192.168.3.131"
localPort = 8081

[[proxies]]
name = "web2"
type = "tcp"
localIP = "192.168.3.131"
localPort = 8080
remotePort = 8080

[[proxies]]
name = "web3"
type = "tcp"
localIP = "192.168.3.131"
localPort = 8082
remotePort = 8085
```
要在frps部署的vps上的防火墙打开对应端口就可以
