### ISSUE TITLE
Port unavailable when port is in fact available

### ISSUE THREAD

**Issue by hykilpikonna** [fatedier/frp#4506]
### Bug Description

![image](https://github.com/user-attachments/assets/a29faf47-8b5e-4a8b-9f26-995d56ba293d)

### frpc Version

0.61.0

### frps Version

0.61.0

### System Architecture

linux/amd64

### Configurations

```toml
bindPort = 999
bindAddr = "51.222.176.204"

auth.method = "token"
auth.token = "..."

allowPorts = [
    {single = 80}
]
```

```toml
serverAddr = "51.222.176.204"
serverPort = 999

[auth]
token = "..."

[[proxies]]
name = "aquadx-allnet"
type = "tcp"
localIP = "127.0.0.1"
localPort = 81
remotePort = 80
```

### Logs

2024-10-23 06:47:57.255 [W] [server/control.go:394] [6ffb8f01cd709bbc] new proxy [aquadx-allnet] type [tcp] error: port unavailable

### Steps to reproduce

1. Have multiple IPv4 on your server
2. Serve port 80 on one IPv4
3. Bind frps to another IPv4
4. Try to create a tunnel that serve on port 80 on this other IPv4 using frps
5. Observe error

### Affected area

- [ ] Docs
- [X] Installation
- [ ] Performance and Scalability
- [ ] Security
- [X] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others
