### ISSUE TITLE
0.61可以提供完整的http2https, https2https的例子么

### ISSUE THREAD

**Issue by shyandsy** [fatedier/frp#4576]
### Bug Description

场景
1. 内网服务器https://192.168.101.20:6443, 是k8s cluster api
2. 公网阿里云服务器 47.xx.xx.xx 是我的公网ip
3. 我希望通过公网https 50080 和 http 55000 端口，访问内网k8s cluster api

尝试http2https，tcp都无法访问内网https服务

### frpc Version

0.61.0

### frps Version

0.61.0

### System Architecture

linux/amd64

### Configurations

server配置
```toml
bindPort = 50000

vhostHTTPPort = 50080
vhostHTTPSPort = 55000

subdomainHost = "xxx.xxx.com"
log.level = "debug"
```

client配置
```toml
# 方式1 tcp
[[proxies]]
name = "kubectl"
type = "tcp"
localIP = "192.168.101.20"
localPort = 6443
remotePort = 52000

# 方式2 http2https
[[proxies]]
name = "k8s"
type = "http"
#customDomains = ["xxx.xxx.com"]
subDomain = "a"
[proxies.plugin]
type = "http2https"
localAddr = "192.168.101.20:6443"
hostHeaderRewrite = "192.168.101.20"
#requestHeaders.set.x-from-where = "a"
```

### Logs

1. 尝试tcp方式访问
server debug输出
![image](https://github.com/user-attachments/assets/6da8b055-71c4-4123-a450-ae93982cd7da)

client debug输出
![image](https://github.com/user-attachments/assets/033e54ea-81de-407c-9715-403fa85e617f)

2. 尝试http方式访问
server debug输出
![image](https://github.com/user-attachments/assets/0488ced8-d3f9-4799-8920-df75c51193aa)

client debug输出
![image](https://github.com/user-attachments/assets/33eac3cd-0472-45c4-a4df-6e0e4e4ea2a2)

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others
