### ISSUE TITLE
Mysterious Network Connection Failure

### ISSUE THREAD

**Issue by NearlyHeadlessJack** [fatedier/frp#4648]
### Bug Description

- 摘要：两个frpc连接同一个frps，其中一个永远正常，另一个经常报`connection refused` , 无法判别是frp的问题还是云服务商的问题。
- 背景：A、B两服务器均运行Minecraft Server，想通过frp将MC服务器的rcon映射到C服务器上进行其他业务操作。 AB服务器使用的frpc，C服务器使用的frps。
- BUG：A服务器的业务完全正常，但B服务器会经常报`connection refused`。(以下用x.x.x.x代替C服务器IP)
情况一：启动连接时正常，过十几分钟就报错：`connect to server error: dial tcp x.x.x.x:7000: connect: connection refused`  
情况二：启动连接都无法进行，如上。

服务端记录，只在连接成功然后突然断联情况下有：
``` 
[control.go:401] [5aa6ff4616974e14] new proxy [rcon1] type [tcp] success
[proxy.go:115] [5aa6ff4616974e14] [rcon1] proxy closing
[proxy.go:201] [5aa6ff4616974e14] [rcon1] listener is closed: accept tcp [::]:10086: use of closed network connection
[control.go:359] [5aa6ff4616974e14] client exit success
```
在情况二下，服务端没有任何记录。

- 网络
C服务器是阿里云ECS，A服务器是甘肃电信家庭宽带，B服务器是河北联通家庭宽带。  
C服务器安全组已放行bindport。

### frpc Version

0.53.2

### frps Version

0.53.2

### System Architecture

linux/amd64

### Configurations

frps.toml
``` toml
bindPort = 7000
token = "okokok123"
```
frpc.toml of Server A
``` toml
serverAddr = "x.x.x.x"
serverPort = 7000
token = "okokok123"

[[proxies]]

name = "rcon"
type = "tcp"
localIP = "127.0.0.1"
localPort = 1001
remotePort = 10085
```
frpc.toml of Server B
``` toml
serverAddr = "x.x.x.x"
serverPort = 7000
token = "okokok123"

[[proxies]]

name = "rcon"
type = "tcp"
localIP = "127.0.0.1"
localPort = 1001
remotePort = 10086
```

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [ ] Installation
- [x] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others
