### ISSUE TITLE
[咨询] 请问代理Http服务时，subdomain与group是否可以同时使用？

### ISSUE THREAD

**Issue by chingxuds** [fatedier/frp#4672]
### Describe the feature request

在查阅文档时，「负载均衡与健康检查」一节中提到可以将多个相同类型的代理加入到同一个 group 中，以实现负载均衡的能力。并且支持http代理类型。现在我想实现一个http服务的负载均衡，同时还想使用自定义二级域名（subdomain），但我在文档中和范例配置文件中均没有找到类似案例，想问下目前的程序是否可以实现？如下配置是否可以正常工作？

期望实现的配置：
```toml
[[proxies]]
name = "web"
type = "http"
localIP = "192.168.1.1"
localPort = 80
subdomain = "web"
loadBalancer.group = "web_balance"
loadBalancer.groupKey = "123"

[[proxies]]
name = "web_fallback"
type = "http"
localIP = "192.168.1.2"
localPort = 80
subdomain = "web"
loadBalancer.group = "web_balance"
loadBalancer.groupKey = "123"
```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [x] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by fatedier** [comment]
是否可以直接执行测试一下？

**Comment by chingxuds** [comment]
> 是否可以直接执行测试一下？

我按照如下配置可以正常启动，目前服务访问也正常。

```toml
[[proxies]]
name = "web"
type = "http"
localIP = "192.168.1.1"
localPort = 80
subdomain = "web"
loadBalancer.group = "web_balance"
loadBalancer.groupKey = "123"
healthCheck.type = "http"
healthCheck.path = "/check"
healthCheck.timeoutSeconds = 3
healthCheck.maxFailed = 3
healthCheck.intervalSeconds = 10

[[proxies]]
name = "web_fallback"
type = "http"
localIP = "192.168.1.2"
localPort = 80
subdomain = "web"
loadBalancer.group = "web_balance"
loadBalancer.groupKey = "123"
healthCheck.type = "http"
healthCheck.path = "/check"
healthCheck.timeoutSeconds = 3
healthCheck.maxFailed = 3
healthCheck.intervalSeconds = 10
```
