### ISSUE TITLE
Better document configuration files with good working examples

### ISSUE THREAD

**Issue by Plarixtu** [fatedier/frp#4711]
### Bug Description

I really struggle to get FRP to work in a docker compose environment. There is always something wrong with the configuration and I can't figure out how it has to be. The style in the format in the README seems to be outdated. 
At first it was hard to figure out, that .ini is outdated. 
Then I had to figure out, that the correct format seems to be the legacy format.
Now when connecting I constantly get errors. 
There aren't any usable working examples on the internet anywhere. I'm close to giving up. Not even ChatGPT is of any help.

Currently on server side I get the error "[control.go:214][W] ProxyName [ssh] is not exist"

### frpc Version

0.9.0

### frps Version

0.9.0

### System Architecture

linux/amd64

### Configurations

My `frpc.toml` file looks like this:

```
[common]
server_addr = my-server.io
server_port = 7000
authentication_method = token
token = MY_SECRET

start = ssh

[ssh]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 6000
```

My `docker-compose.yml`

```
services:
  frpc:
    image: fatedier/frp:latest
    container_name: frpc
    volumes:
      - ./frpc.toml:/etc/frp/frpc.toml:ro
    network_mode: "host"
    entrypoint: ["/frpc", "-c", "/etc/frp/frpc.toml", "--log-level=debug"]
    restart: always
```

Start with

```
docker compose up -d
docker compose logs -f
```

### Logs

frpc  | 2025/03/14 06:08:20 [control.go:185][E] ProxyName [ssh], start proxy error, ProxyName [ssh] is not exist
frpc  | 2025/03/14 06:08:20 [control.go:39][E] ProxyName [ssh], connect to server failed!
frpc  | 2025/03/14 06:08:20 [main.go:112][W] All proxy exit!
frpc exited with code 0

### Steps to reproduce

```
docker compose up -d
docker compose logs -f
```

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [x] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [x] Client Plugin
- [x] Server Plugin
- [ ] Extensions
- [ ] Others
