### ISSUE TITLE
docker环境中，容器启动后没有监听dashboard？

### ISSUE THREAD

**Issue by fhxzho** [fatedier/frp#4759]
### Bug Description

你好@fatedier
我使用docker运行frps时，在frps.toml文件做了dashboard相关配置，容器映射了7500端口。
但是在容器日志里却发现没有监听dashboard的记录，尝试了非docker环境是正常有监听的，这个是正常的吗？是不是有特殊配置？

### frpc Version

0.62.0

### frps Version

0.62.0

### System Architecture

linux/amd64

### Configurations

frps.toml
bindPort = 7000
auth.method = "token"
auth.token = "111"

webServer.port = 7500
webServer.addr = "0.0.0.0"
webServer.user = "111"
webServer.password = "111"
-----------------------------------------
frps.yml
version: '3'

services:
  frps:
    image: ghcr.io/fatedier/frps:v0.62.0
    container_name: frps
    ports:
      - 7000:7000
      - 7500:7500
    volumes:
      - /frp/frps.toml:/etc/frp/frps.toml
    restart: always

### Logs

[root@Daniel frp]# docker ps -a
CONTAINER ID   IMAGE                           COMMAND           CREATED         STATUS         PORTS                                                                                  NAMES
0956a8dc40b5   ghcr.io/fatedier/frps:v0.62.0   "/usr/bin/frps"   8 seconds ago   Up 7 seconds   0.0.0.0:7000->7000/tcp, :::7000->7000/tcp, 0.0.0.0:7500->7500/tcp, :::7500->7500/tcp   frps
[root@Daniel frp]#
[root@Daniel frp]# docker logs -f frps
2025-04-17 10:31:48.260 [I] [frps/root.go:107] frps uses command line arguments for config
2025-04-17 10:31:48.877 [I] [server/service.go:237] frps tcp listen on 0.0.0.0:7000
2025-04-17 10:31:48.878 [I] [frps/root.go:114] frps started successfully
^C

### Steps to reproduce

1. 
2. 
3. 
...

### Affected area

- [ ] Docs
- [x] Installation
- [ ] Performance and Scalability
- [ ] Security
- [ ] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others

**Comment by blue-cloud-net** [comment]
补上这个试试  command: -c /etc/frp/frps.toml

docker镜像里好像默认没有使用配置文件 _/etc/frp/frps.toml_

``` yml
  frps:
    image: ghcr.io/fatedier/frps:v0.62.0
    container_name: frps
    command: -c /etc/frp/frps.toml
    ports:
      - 7000:7000/tcp
      - 7000:7000/udp
      - 7001:7001/udp
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/docker_volumes/frp/conf:/etc/frp'
    environment:
      TZ: 'Asia/Shanghai'
    restart: always
```
