### ISSUE TITLE
[Feature Request] yaml config should ignore field start with dot to support yaml merge

### ISSUE THREAD

**Issue by wenerme** [fatedier/frp#4775]
### Describe the feature request

to help reuse some config like

```yaml
.common: &common
  type: stcp
  secretKey: "{{.Envs.FRPC_SECRET_KEY}}"
  localIp: 127.0.0.1
  allowUsers: [ '*' ]
  transport:
    useEncryption: true
    useCompression: true

proxies:
- name: ssh
  localPort: 22
  <<: *common

- name: pg
  localPort: 5432
  <<: *common

- name: web
  localPort: 80
  <<: *common
```

but this is not supported by frp, this is very common pattern for docker compose yaml, github action yaml etc.

### Affected area

- [ ] Docs
- [ ] Installation
- [ ] Performance and Scalability
- [ ] Security
- [x] User Experience
- [ ] Test and Release
- [ ] Developer Infrastructure
- [ ] Client Plugin
- [ ] Server Plugin
- [ ] Extensions
- [ ] Others
