### ISSUE TITLE
[FEATURE REQUEST] multi server

### ISSUE THREAD

**Issue by jinyu121** [fatedier/frp#632]
**Expected Configures**

```
[common]
server_addr = 1.1.1.1
server_port = 7000
log_level = warn
login_fail_exit = false
user = My-Computer

[ssh-1]    # It connect to 1.1.1.1
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 1022

[ssh-2]    # Notice here, it should connect 2.2.2.2
server_addr = 2.2.2.2
server_port = 7000
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 2022
```

`[ssh-2]` should use its own `server-addr` and `server-port`.

I mean, if specialized, each connection should use its own config, including server and port, rather than the global `server-addr` and `server-port`

----

If 1.1.1.1 died, I can still connect to my client via 2.2.2.2 -- That's a double insurance.

**Comment by BI7PRK** [comment]
run an new client.

**Comment by fatedier** [comment]
It's not necessary.

**Comment by fatedier** [comment]
@libracoder Not in the short-term plan.

**Comment by silent-tan** [comment]
> run an new client.

yet, can i run multiple client in one machine? for example:

container1
```toml
[common]
server_addr = 1.1.1.1
server_port = 7000
log_level = warn
login_fail_exit = false
user = My-Computer

[ssh-1]    # It connect to 1.1.1.1
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 1022
```

container2
```toml
[common]
server_addr = 2.2.2.2
server_port = 7001
log_level = warn
login_fail_exit = false
user = My-Computer

[ssh-1]    # It connect to 2.2.2.2
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 1022
```
